# Trigger build and analysis on sonarcloud when pushing in dev or pull_request
#   and when creating a pull_request
name: Build and analisys on sonarcloud
on:
  push:
    branches:
        - dev
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
          java-version: 17
    - name: Build
      run: ./gradlew stage

  sonarcloud:
    name: Analysis with sonarcloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
