name: java build and test
on:
  push:
    branch: main
  pull_request:
    types: [opened, syncronize, reopened]
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # shallow clones disabled
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build and test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # needed to get PR info
        run: ./gradlew build test
