name: deploy
on:
  push:
    branches:
        - main
        - dev

jobs:
  build:
    name: deploy to heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "criptop2p-grupoo" #Must be unique in Heroku
          heroku_email: "jcfstabile@gmail.com"
